services:
  db:
    image: raulzito311/acmesf-db
    build: ./db/.
    ports: 
      - "3306:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
  api:
    image: raulzito311/acmesf-api
    build: ./AcmeSF/api/.
    depends_on:
      db:
        condition: service_started
    ports: 
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
  app:
    image: raulzito311/acmesf
    build: ./AcmeSF/.
    depends_on:
      api:
        condition: service_started
    ports: 
      - "5173:5173"